    </div> <!-- fin div main --> 
  </div> <!-- fin div contenaire -->

  <div id="footer">
    <!-- <hr/> horinzontal line-->
    <!--
      <p>
        <a href="http://validator.w3.org/check?uri=referer">
          <img src="http://www.w3.org/Icons/valid-xhtml10" title ="Valid XHTML 1.0!" alt="Valid XHTML 1.0!" height="31" width="88" />
        </a>
        <a href="http://www.spreadfirefox.com/?q=affiliates&amp;id=0&amp;t=70"><img alt="Get Firefox!" title="Get Firefox!" src="http://sfx-images.mozilla.org/affiliates/Buttons/88x31/get.gif"/></a>
      </p>
    -->
  </div> <!--footer-->
	<!-- TIMINGS: <?php echo "generated in ".(microtime(1)-$page_start_time)."s" ?> -->
</body>
</html>
<?php

  mysql_close();

?>
