<?php
$strings =
array(
	"en" => array(
				"boat" => "Boat",
				"waypoint" => "WayPoint",
				"course" => "Course",
				"orthodromic distance" => "Orthodromic distance",
				"orthodromic course" => "Orthodromic course",
				"loxodromic distance" => "Loxodromic distance",
				"loxodromic course" => "Loxodromic course",
				"wind" => "Wind",
				"speed" => "Speed",
				"direction" => "Direction",
				"best course / speed" => "Best course / speed",
				"boat/wind angle" => "Boat/wind angle",
				"vmg" => "VMG",
				"validate" => "Validate",
				"taverne" => "Forum VLM &quot;La Taverne&quot;",
				"help" => "Help",
				"error" => "Error",
				"the wind speed" => "The wind speed",
				"wrong data" => "wrong data",
				"average speed" => "Average speed",
				"distance" => "Distance",
				"total time" => "Total time",
				"time" => "Time",
				"waypoint" => "Waypoint",
				"direct road" => "Direct road",
				"optimum road" => "Optimum road",
				"vmg info" => "VMG Info"
				
				),


	"fr" => array(
				"boat" => "Bateau",
				"waypoint" => "WayPoint",
				"course" => "Cap",
				"orthodromic distance" => "Distance orthodromique",
				"orthodromic course" => "Cap orthodromique",
				"loxodromic distance" => "Distance loxodromique",
				"loxodromic course" => "Cap loxodromique",
				"wind" => "Vent",
				"speed" => "Vitesse",
				"direction" => "Direction",
				"best course / speed" => "Meilleur cap / vitesse",
				"boat/wind angle" => "Angle bateau/vent",
				"vmg" => "VMG",
				"validate" => "Valider",
				"taverne" => "Forum VLM &quot;La Taverne&quot;",
				"help" => "Aide",
				"error" => "Erreur",
				"the wind speed" => "La vitesse du vent",
				"wrong data" => "Donnees incorrectes",
				"average speed" => "Vitesse moyennne",
				"distance" => "Distance",
				"total time" => "Temps total",
				"time" => "Temps",
				"waypoint" => "Waypoint",
				"direct road" => "Route directe",
				"optimum road" => "Route optimum",
				"vmg info" => "Info. VMG"

				

				)
	);
	
?>
