<?php

/*
 * phpMyEdit language file
 *
 * language: basque
 * encoding: iso-8859-1
 * date: 2004-05-11
 * author: Ibon Igartua <ibon@zuhar.net>
 */

/* $Platon: phpMyEdit/lang/PME.lang.EU.inc,v 1.1 2004/05/17 10:53:06 nepto Exp $ */

return Array(
		'Add'           =>'Gehitu',
		'Copy'         	=>'Kopiatu',
		'Change'        =>'Aldatu',
		'Delete'        =>'Ezabatu',
		'View'      	=>'Ikusi',
		'Prev'          =>'Aurrekoa',
		'Next'          =>'Hurrengoa',
		'First'         =>'Lehena',
		'Last'          =>'Azkena',
		'Go to'         =>'Joan',
		'Page'          =>'Orrialdea',
		'Records'       =>'Erregistroak',
		'Save'          =>'Gorde',
		'More'          =>'Gehiago',
		'Apply'         =>'Aplikatu',
		'Cancel'        =>'Utzi',
		'Search'		=>'Bilatu',
		'Hide'			=>'Ezkutatu',
		'Clear'			=>'Garbitu',
		'Query'			=>'Kontsulta',
		'Current Query'	=>'Uneko Kontsulta',
		'Sorted By'		=>'Orden Irizpidea',
		'ascending'		=>'gorantz',
		'descending'	=>'beherantz',
		'hidden'		=>'ezkutukoa',
		'of'			=>'-',
		'record added'  =>'erregistroa gehituta',
		'record changed'=>'erregistroa aldatuta',
		'record deleted'=>'erregistroa ezabatuta',
		'Please enter'  =>'Mesedez, sartu ezazu ',
		'months'	=> Array(
			'01'=>'urtarrila',
			'02'=>'otsaila',
			'03'=>'martxoa',
			'04'=>'apirila',
			'05'=>'maiatza',
			'06'=>'ekaina',
			'07'=>'uztaila',
			'08'=>'abuztua',
			'09'=>'iraila',
			'10'=>'urria',
			'11'=>'azaroa',
			'12'=>'abendua'),
		// phpMyEdit-report
		'Make report'			=> 'Txostena sortu',
		'Select fields'			=> 'Eremuak aukertau',
		'Records per screen'	=> 'Erregistroak orrialdeko',
		);

?>
