<?php

/*
 * phpMyEdit language file
 *
 * language: polish
 * encoding: utf-8
 * date: 2002-10-01, 2003-06-30
 * author: Piotr Walesiuk <p.walesiuk@bos.com.pl>
 */

/* $Platon: phpMyEdit/lang/PME.lang.PL-UTF8.inc,v 1.1 2007-09-16 12:57:13 nepto Exp $ */

return Array(
		'Add'          	=>'Dodaj',
		'Copy'         	=>'Kopiuj',
		'Change'       	=>'Zmień',
		'Delete'       	=>'Usuń',
		'View'      	=>'Pokaż',
		'Prev'         	=>'Wstecz',
		'Next'         	=>'Dalej',
		'First'         =>'First', // untranslated
		'Last'          =>'Last',  // untranslated
		'Go to'         =>'Go to', // untranslated
		'Page'         	=>'Strona',
		'Records'      	=>'Rekordy',
		'Save'          =>'Zapisz',
		'More'          =>'Więcej',
		'Apply'         =>'Zastosuj',
		'Cancel'        =>'Anuluj',
		'Search'	=>'Szukaj',
		'Hide'		=>'Ukryj',
		'Clear'		=>'Wyczyść',
		'Query'		=>'Zapytanie',
		'Current Query'	=>'Aktualne zapytanie',
		'Sorted By'		=>'Posortowane według',
		'ascending'		=>'rosnąco',
		'descending'	=>'malejąco',
		'hidden'		=>'ukryte',
		'of'            =>'z',
		'record added'  =>'rekord dodany',
		'record changed'=>'rekord zmieniony',
		'record deleted'=>'rekord usunięty',
		'Please enter'  =>'Proszę wprowadzić',
		'months'	=> Array(
			'01'=>'Styczeń',
			'02'=>'Luty',
			'03'=>'Marzec',
			'04'=>'Kwiecień',
			'05'=>'Maj',
			'06'=>'Czerwiec',
			'07'=>'Lipiec',
			'08'=>'Sierpień',
			'09'=>'Wrzesień',
			'10'=>'Październik',
			'11'=>'Listopad',
			'12'=>'Grudzień')
		);

?>
