<?php

/*
 * phpMyEdit language file
 *
 * language: slovak
 * encoding: utf-8
 * date: 2002-02-02, 2003-05-01
 * author: Ondrej Jombik <nepto@php.net>
 */

/* $Platon: phpMyEdit/lang/PME.lang.SK-UTF8.inc,v 1.1 2007-09-16 12:57:13 nepto Exp $ */

return Array(
		'Add'          	=>'Pridať',
		'Copy'         	=>'Kopírovať',
		'Change'       	=>'Zmeniť',
		'Delete'       	=>'Zmazať',
		'View'      	=>'Pozrieť',
		'Prev'         	=>'Predchádzajúci',
		'Next'         	=>'Ďalší',
		'First'         =>'Prvý',
		'Last'          =>'Posledný',
		'Go to'         =>'Choď na',
		'Page'         	=>'Stránka',
		'Records'      	=>'Záznamov',
		'Save'          =>'Uložiť',
		'More'          =>'Viac',
		'Apply'         =>'Použiť',
		'Cancel'        =>'Storno',
		'Search'		=>'Hľadať',
		'Hide'			=>'Skryť',
		'Clear'			=>'Zrušiť',
		'Query'			=>'Vyhľadať',
		'Current Query'	=>'Aktuálny dotaz',
		'Sorted By'		=>'Usporiadané podľa',
		'ascending'		=>'vzostupne',
		'descending'	=>'zostupne',
		'hidden'		=>'skryté',
		'of'			=>'z',
		'record added'  =>'záznam pridaný',
		'record changed'=>'záznam zmenený',
		'record deleted'=>'záznam zmazaný',
		'Please enter'  =>'Prosím zadajte',
		'months'	=> Array(
			'01'=>'Január',
			'02'=>'Február',
			'03'=>'Marec',
			'04'=>'Apríl',
			'05'=>'Máj',
			'06'=>'Jún',
			'07'=>'Júl',
			'08'=>'August',
			'09'=>'September',
			'10'=>'Október',
			'11'=>'November',
			'12'=>'December'),
		// phpMyEdit-report
		'Make report'			=> 'Vytvoriť report',
		'Select fields'			=> 'Vybrať stĺpce',
		'Records per screen'	=> 'Počet záznamov na stránke',
		);

?>
