<?php

/*
 * phpMyEdit language file
 *
 * language: catalŕ
 * encoding: utf-8
 * date: 2006-04-06
 * author: Josep Maria Faura <j.m.faura@telefonica.net>
 */

/* $Platon: phpMyEdit/lang/PME.lang.CA-UTF8.inc,v 1.1 2007-09-16 12:57:12 nepto Exp $ */

return Array(
		'Add'           =>'Afegir',
		'Copy'         	=>'Copiar',
		'Change'        =>'Modificar',
		'Delete'        =>'Suprimir',
		'View'      	=>'Visualitzar',
		'Prev'          =>'Anterior',
		'Next'          =>'Següent',
		'First'         =>'Primer', 
		'Last'          =>'Últim',  
		'Go to'         =>'Ves a', 
		'Page'          =>'Pŕgina',
		'Records'       =>'Registres',
		'Save'          =>'Salvar',
		'More'          =>'Més',
		'Apply'         =>'Aplicar',
		'Cancel'        =>'Cancelˇlar',
		'Search'	=>'Cercar',
		'Hide'		=>'Amagar',
		'Clear'		=>'Netejar',
		'Query'		=>'Consultar',
		'Current Query'	=>'Consulta actual',
		'Sorted By'	=>'Ordenat per',
		'ascending'	=>'ascendent',
		'descending'	=>'descendent',
		'hidden'	=>'amagat',
		'of'		=>'de',
		'record added'  =>'Registre afegit',
		'record changed'=>'Registre modificat',
		'record deleted'=>'Registre esborrat',
		'Please enter'  =>'Sisplau introdueixi ',
		'months'	=> Array(
			'01'=>'Gener',
			'02'=>'Febrer',
			'03'=>'Març',
			'04'=>'Abril',
			'05'=>'Maig',
			'06'=>'Juny',
			'07'=>'Juliol',
			'08'=>'Agost',
			'09'=>'Septembre',
			'10'=>'Octubre',
			'11'=>'Novembre',
			'12'=>'Desembre'),
		// phpMyEdit-report
		'Make report'	=> 'Construir informe',
		'Select fields'	=> 'Seleccionar camps',
		'Records per screen'	=> 'Registres per pantalla',
		);

?>
