<?php

/*
 * phpMyEdit language file
 *
 * language: english (United States)
 * encoding: iso-8859-1
 * date: 2002-02, 2003-05-01
 * author: Jim Kraai <jkraai@users.sourceforge.net>
 */

/* $Platon: phpMyEdit/lang/PME.lang.EN-US.inc,v 1.10 2004/12/27 20:14:29 nepto Exp $ */

return Array(
		'Add'           	=>'Add',
		'Copy'           	=>'Copy',
		'Change'       		=>'Change',
		'Delete'        	=>'Delete',
		'View'	     	 	=>'View',
		'Prev'          	=>'Prev',
		'Next'          	=>'Next',
		'First'         	=>'First',
		'Last'          	=>'Last',
		'Go to'         	=>'Go to',
		'Page'          	=>'Page',
		'Records'       	=>'Records',
		'Save'          	=>'Save',
		'More'          	=>'More',
		'Apply'         	=>'Apply',
		'Cancel'        	=>'Cancel',
		'Search'			=>'Search',
		'Hide'				=>'Hide',
		'Clear'				=>'Clear',
		'Query'				=>'Query',
		'Current Query'		=>'Current Query',
		'Sorted By'			=>'Sorted By',
		'ascending'			=>'ascending',
		'descending'		=>'descending',
		'hidden'			=>'hidden',
		'of'				=>'of',
		'record added'  	=>'record added',
		'record changed'	=>'record changed',
		'record deleted'	=>'record deleted',
		'Please enter'  	=>'Please enter',
		'months' => Array(
			'01'=>'January',
			'02'=>'February',
			'03'=>'March',
			'04'=>'April',
			'05'=>'May',
			'06'=>'June',
			'07'=>'July',
			'08'=>'August',
			'09'=>'September',
			'10'=>'October',
			'11'=>'November',
			'12'=>'December'),
		// phpMyEdit-report
		'Make report'			=> 'Make report',
		'Select fields'			=> 'Select fields',
		'Records per screen'	=> 'Records per screen',
		);

?>
