#!/bin/sh
#
# combine source code into one module
# easier to compile -- no make file needed
#
# pretty generic script -- just echos, cats and greps.
# 

echo "combining source code into one module"
echo "output is wgrib.c"
set -x

h="bds.h bms.h cnames.h gds.h grib.h pds4.h"
c="wgrib_main.c seekgrib.c ibm2flt.c readgrib.c intpower.c cnames.c \
	BDSunpk.c flt2ieee.c wrtieee.c levels.c PDStimes.c missing.c \
        nceptable_opn.c nceptable_reanal.c  nceptab_131.c nceptab_130.c nceptab_128.c \
        ectable_128.c ectable_129.c ectable_130.c ectable_131.c \
        ectable_140.c ectable_150.c ectable_151.c ectable_160.c ectable_170.c \
        ectable_172.c ectable_180.c ectable_190.c nceptab_129.c \
        ec_ext.c gds_grid.c gribtable.c PDS_date.c ensemble.c \
	dwdtable_002.c dwdtable_201.c dwdtable_202.c dwdtable_203.c \
        dwdtable_204.c dwdtable_205.c cptectable_254.c BDS_NValues.c"

echo >wgrib.c "#include <stdio.h>"
echo >>wgrib.c "#include <stdlib.h>"
echo >>wgrib.c "#include <string.h>"
echo >>wgrib.c "#include <stddef.h>"
echo >>wgrib.c "#include <math.h>"
echo >>wgrib.c "#include <float.h>"


cat $h >>wgrib.c

cat $c | grep -v '#include' >> wgrib.c

#find version number

set -x

version="v`grep "#define VERSION" wgrib.c | sed -e 's/.*\"v//' -e 's/ .*//'`"


if [ "$1" = "alpha" ] ; then
  exit 
fi

if [ "$1" = "beta" ] ; then
   scp wgrib.c wd51we@rzdm:ftp/wgrib/wgrib.c.beta
   exit
fi


tar -cvf wgrib.tar $h $c src2all makefile Changes

scp wgrib.c wd51we@rzdm:ftp/wgrib/wgrib.c.beta
scp wgrib.c wd51we@rzdm:ftp/wgrib/wgrib.c.$version
scp wgrib.tar wd51we@rzdm:ftp/wgrib/wgrib.tar.$version
scp Changes wd51we@rzdm:ftp/wgrib/Changes
