<?php

/*
 * phpMyEdit language file
 *
 * language: spanish (mexican)
 * encoding: iso-8859-1
 * date: 2003-04-30
 * author: unknown
 */

/* $Platon: phpMyEdit/lang/PME.lang.ES-MX-LATIN1.inc,v 1.1 2007-09-16 12:57:12 nepto Exp $ */

return Array(
		'Add'           =>'Agregar',
		'Copy'         	=>'Copiar',
		'Change'        =>'Cambiar',
		'Delete'        =>'Suprimir',
		'View'      	=>'Ver',
		'Prev'          =>'Anterior',
		'Next'          =>'Siguiente',
		'First'         =>'First', // untranslated
		'Last'          =>'Last',  // untranslated
		'Go to'         =>'Go to', // untranslated
		'Page'          =>'Página',
		'Records'       =>'Registros',
		'Save'          =>'Guardar',
		'More'          =>'Más',
		'Apply'         =>'Aplicar', 
		'Cancel'        =>'Cancelar',
		'Search'		=>'Buscar',
		'Hide'			=>'Ocultar',
		'Clear'			=>'Limpiar',
		'Query'			=>'Consulta SQL',
		'Current Query'	=>'Consulta actual', 
		'Sorted By'		=>'Ordenado por', 
		'ascending'		=>'ascendente', 
		'descending'	=>'descendente',
		'hidden'		=>'oculto',
		'of'			=>'de',
		'record added'  =>'registro agregado',
		'record changed'=>'registro cambiado',
		'record deleted'=>'registro borrado',
		'Please enter'  =>'Por favor introduzca ',
		'months'	=> Array(
				'01'=>'Enero',
				'02'=>'Febrero',
				'03'=>'Marzoa',
				'04'=>'Abril',
				'05'=>'Mayo',
				'06'=>'Junio',
				'07'=>'Julio',
				'08'=>'Agosto',
				'09'=>'Septiembre',
				'10'=>'Octubre',
				'11'=>'Noviembre',
				'12'=>'Diciembre'),
		// phpMyEdit-report
		'Make report'			=> 'Make report',
		'Select fields'			=> 'Select fields',
		'Records per screen'	=> 'Records per screen',
		);

?>
